### ISSUE TITLE
Unable to create function

### ISSUE THREAD

**Issue by heymartinadams** [graphcool-examples/functions#22]
Getting the following error, am unable to create an SSS function.
![image](https://user-images.githubusercontent.com/11673745/28250425-c99536a0-6a1c-11e7-8cc7-2cf3852e89f9.png)

**Comment by heymartinadams** [comment]
FYI, able to neither create new nor update existing functions.

**Comment by heymartinadams** [comment]
Could it be that the function itself isn’t working? Just found this: https://github.com/graphcool/api-bugs/issues/83

If so, might be good to have a different feedback mechanism.

**Comment by marktani** [comment]
Yes I was about to say as much. This behaviour is observed when you have a syntax error in the function itself, or we were not able to import a specified npm module or similar.

We're already working on returning a user friendly error message in these cases instead 🙂 Could you check your code for syntax errors? (might be a missing bracket or brace, for example)

**Comment by heymartinadams** [comment]
Thanks! Will check the code again.

**Comment by marktani** [comment]
Just noticed this is the `functions` repo. For the future, please report errors like this in `https://github.com/graphcool/api-bugs/` instead. Let's discuss this error here though 🙂

**Comment by heymartinadams** [comment]
Ok. FYI, here’s the `query` and `function`.

```graphql
subscription {
  User(filter: {
    mutation_in: [CREATED]
  }) {
    updatedFields
    node {
      id
      firstName
      lastName
      email
      isPaid
    }
  }
}
```

```javascript
module.exports = function (event) {
  var sg = require("sendgrid@4.7.0")(___SENDGRID_API___)
  var request = sg.emptyRequest()
  request.body = [{
    "email": event.data.node.email,
    "first_name": event.data.node.firstName,
    "last_name": event.data.node.lastName,
    "LPA_paid": event.data.node.isPaid,
    "SOURCE": "LPA"
  }];
  request.method = "POST"
  request.path = "/v3/contactdb/recipients"
  return new Promise(function(resolve, reject) {
    sg.API(request, function (error, response) {
      if (error) {
        console.log("Error response received")
        reject(error)
      }
      console.log(response.statusCode)
      console.log(response.body)
      console.log(response.headers)
      resolve(response)
    })
  }
}
```

**Comment by heymartinadams** [comment]
Downgraded `sendgrid` from `@4.7.0` to `@3.0.7` as per https://tehsis.github.io/webtaskio-canirequire/#sendgrid (they must have changed it—it used to be 4.7.0, will create PR for other sendgrid example). Still not working. Will keep checking.

**Comment by marktani** [comment]
Can you try

**Comment by heymartinadams** [comment]
Is the API key wrapped as a "string"? Tried both.

**Comment by marktani** [comment]
yes, it is

**Comment by heymartinadams** [comment]
For reference: https://github.com/sendgrid/sendgrid-nodejs/blob/master/examples/contactdb/contactdb.js#L253-L279

**Comment by heymartinadams** [comment]
Per @marktani: You missed a `)` in the second last line, this is the correct code you need to use


```
module.exports = function (event) {
  var sg = require("sendgrid")(___SENDGRID_API_KEY___)
  var request = sg.emptyRequest()
  request.body = [{
    "email": event.data.node.email,
    "first_name": event.data.node.firstName,
    "last_name": event.data.node.lastName
  }];
  request.method = "POST"
  request.path = "/v3/contactdb/recipients"
  return new Promise(function(resolve, reject) {
    sg.API(request, function (error, response) {
      if (error) {
        console.log("Error response received")
        reject(error)
      }
      console.log(response.statusCode)
      console.log(response.body)
      console.log(response.headers)
      resolve(response)
    })
  })
}
```

**Comment by marktani** [comment]
Thanks!
