### ISSUE TITLE
Auth0-authentication: using npm modules in webtask.io

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool-examples/functions#27]
https://github.com/graphcool-examples/functions/blob/master/auth0-authentication/README.md#variant-2-setup-the-authentication-function-with-webtaskio

If you have a package.json available in the folder where your Javascript file is located, webtask will deploy any module in it when you `wt create` a webtask. So you can use any npm module, just add it to package.json.

**Comment by kbrandwijk** [comment]
See #28

**Comment by marktani** [comment]
Just merged #28, thanks!
