### ISSUE TITLE
AuthenticateEmailUser Issue

### ISSUE THREAD

**Issue by BoraKilicoglu** [graphcool-examples/functions#59]
I'm getting this issue at authenticateEmailUser.js

GraphQL error: function execution error: Error: Graphcool must be instantiated with a pat when calling 'generateAuthToken': new Graphcool('project-id', {pat: 'pat'})

**Comment by marktani** [comment]
You need to create a PAT in your project that's called the same as your function.

**Comment by BoraKilicoglu** [comment]
Solved, thank you 👍

**Comment by Anujraval24** [comment]
what is PAT exactly? 
`event.context.graphcool.pat` is this what are you talking about?
@marktani
