### ISSUE TITLE
email-user-management An unexpected error occured

### ISSUE THREAD

**Issue by in-html** [graphcool-examples/functions#79]
Hello!
Help me please. I want to update user password. I copied the schema code and logic according to the instructions. Next I created a pta on the AUTHENTICATION tab.
I call a mutation:
```
mutation {
 updatePassword(email: "user_email", password: "pass", newPassword: "new_pass") {
    id
 }
}
```
But I get an error: 'GraphQL error: function execution error: An unexpected error occured.'.

If I do the 'test run':
```
{
    "data": {
        "email": "user_email",
        "password": "pass",
        "newPassword": "new_pass",
    },
    "context": {
        "projectId": "projectId",
        "pat": "pat",
  },
}
```
I get an error:

> No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://console.graph.cool' is therefore not allowed access. The response had HTTP status code 502. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> fullscreen:1 Uncaught (in promise) TypeError: Failed to fetch

Tell me please, what could be the problem?

**Comment by huan** [comment]
@in-html I ran into this issue today.

Had you fixed it?

**Comment by anton0243** [comment]
We fixed this. But it was a long time ago. I hardly remember. 
It seems that something was connected with permissions.

**Comment by huan** [comment]
Thanks for the reply!

My issue is related the `subscription` part of graphcool. It seems that the Query & Mutation part of HTTP link worked but the WebSocket WSS endpoint not.
